Scranton()
    JIM paper1, paper2
    CLIENT IS ASKING FOR (paper1, paper2)
    IF TOBY IS NOT HERE and paper1 < paper2:
        GET ME A COPY OF ("The first number is greater")
    HEI TOBY IS HERE OH WAIT IT WASNT HIM SO IF paper1 > paper2:
        GET ME A COPY OF ("The second number is greater")
    LOOK TOBY IS COMING:
        GET ME A COPY OF ("The numbers are equal")
    DAMN TOBY ARRIVED
FIRE!