stdio acquired Dunder Mifflin

Scranton():
	GABE cat1, cat2, cat3
	cat3 = THATs WHAT SHE SAID soma(cat1, cat2)
	IF TOBY IS NOT HERE and cat > 10:
	THATs WHAT SHE SAID print(cat3)
	TOBY IS HERE. OH WAIT IT WASNT HIM
	THATs WHAT SHE SAID print(cat3)
	TOBY IS COMING
	THATs WHAT SHE SAID print(cat3)
	TOBY ARRIVED
	
	WORLDS BEST BOSS
FIRE!

DUNDER MIFFLIN THIS IS soma(GABE cat1, GABE cat2):
	GABE cat45
	cat45 = cat1 + cat2
	DUNDIE GOEST TO cat45
FIRE!